### ISSUE TITLE
Not able to open example projects

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#151]
I can open my own projects with the open-button in the bottom-row. 
But that open-button and bottom-row are not visible with the example projects in the IDE.

**Comment by renaudpawlak** [comment]
I have had difficulties to understand your feedbacks lately. It looks like you have layouts issues because your screen is smaller than mine or something like that, but in general, that sort of issue should be solved by changing the zoom of the browser or by scrolling down to see more of the page. I would appreciate if you send me a screenshot again on this problem, because I cannot guess what is really happening from your text :(

**Comment by HFolkertH** [comment]
Hi Renaud,

I am using Dlite on my iPad, android phone and macbook. The macbook of course shows everything normal. But the Ipad en phone sometimes  (using Chrome) have problems showing the left, top, right or bottom menu-bar/panels. But mostly display is okay. It's difficult to reproduce it.

**Comment by renaudpawlak** [comment]
Good news is: I have just bought an IPAD, so I will be able to make it better eventually :)

**Comment by HFolkertH** [comment]
Hi Renaud,

hopefully your iPad will not distract you to much from further improving dLite.😀
And the ipad is very usefull to test the new camera source. But how does the camera work? I used a button to fire the captureImage action but nothing happens.
