### ISSUE TITLE
not possible to clear a date in datapicker()

### ISSUE THREAD

**Issue by HFolkertH** [cincheo/daquota#36]
Hi Renaud,

Tried all kinds of tricks but there seems to be no way that you can clear/empty a date in the datepicker.
Sometimes one needs to clear a date.

**Comment by renaudpawlak** [comment]
Indeed, there are two issues that have been fixed in the new release (0.9.16)

1. There were no options to enable date reset => that's fixed! I have added the options in date and time pickers to clear/reset the date (in the properties panel, check the "Reset button" option).
2. I think you must have tried to create a button to clear the data in the date picker. I have noticed that the ``clear()`` function fails to proceed when your data is bound to a field (and/or?) to another data. Which is the main use case. I have fixed that problem too. You can for instance try the following code, which clear the date in the date picker when you press the button:

```json
{
  "cid": "container-0",
  "type": "ContainerView",
  "layout": "block",
  "components": [
    {
      "cid": "datepicker-0",
      "type": "DatepickerView",
      "label": "",
      "disabled": false,
      "eventHandlers": [],
      "field": "date",
      "dataSource": "$parent"
    },
    {
      "cid": "button-0",
      "type": "ButtonView",
      "dataSource": "$parent",
      "label": "Clear date",
      "buttonType": "button",
      "variant": "secondary",
      "size": "default",
      "pill": false,
      "squared": false,
      "block": false,
      "disabled": false,
      "eventHandlers": [
        {
          "global": false,
          "name": "@click",
          "actions": [
            {
              "targetId": "container-0",
              "name": "eval",
              "description": "Default action",
              "argument": "$d(target).date = undefined"
            }
          ]
        }
      ]
    }
  ],
  "defaultValue": "={}",
  "eventHandlers": []
}
```

**Comment by HFolkertH** [comment]
Hello Renaud,

Thanks very much for this quick fix.
But there is something strange: 
![image](https://user-images.githubusercontent.com/22573455/171861011-19eb9332-2285-4f9c-abe0-cc6ec82198d9.png)

It says that _undefined_ is a valid expression. But clicking the button gives an error.

I need to put undefined within quotes   ->. "Undefined". Then it works fine. Those quotes are necessary?

![image](https://user-images.githubusercontent.com/22573455/171861400-07714131-2991-4ffd-b3b4-1be7a89b7148.png)

**Comment by renaudpawlak** [comment]
That is not normal indeed. I have pushed a new version with a couple of fixes. The useless ``undefined`` is not visible in the condition and arguments. I have also fixed to update issues in the data.

Now, to clear the data from your date picker, the best way is to use the ``clear()`` action. You can call ``setData(data)``, but passing ``undefined`` as the data will fail, because the data argument is mandatory, and ``undefined`` also means "no argument" in JavaScript. 

So, in that case, the best value to be passed is the ``null`` value. I might want to change the ``setData(data)`` implementation and allow ``undefined`` data to behave like a clear... However I have to think about it a little more.
